mysite/food/urls.py
from django.urls import path
from food import views
app_name = 'food'
urlpatterns = [
    path('', views.index, name='index'),
    path('item/', views.item, name='item'),
    path('<int:item_id>/', views.detail, name='detail')
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('food/', include('food.urls')),
    path('admin/', admin.site.urls),
]

mysite/food/views.py
from django.shortcuts import render
from django.http import HttpResponse
from food.models import Item

# Create your views here.


def index(request):
    item_list = Item.objects.all()
    context = {
        'item_list': item_list,
    }
    return render(request, 'food/index.html', context)


def item(request):
    return HttpResponse('This is a item view')


def detail(request, item_id):
    item = Item.objects.get(pk=item_id)
    context = {
        'item': item
    }
    return render(request, 'food/detail.html', context)

mysite/food/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'food/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a href="#" class="navbar-brand">Food</a>
        <div class="collapse navbar-collapse">
            <div class="navbar-nav ms-auto">
                <a class="nav-item nav-link" href="#">Add Item</a>
                <a class="nav-item nav-link" href="#">Delete Item</a>
                <a class="nav-item nav-link" href="#">View Item</a>
            </div>
        </div>
    </nav>

    {% block body %}
    {% endblock %}
</body>
</html>

mysite/food/templates/food/detail.html
{%extends 'food/base.html'%}
{%block body%}
<h1>{{item.item_name}}</h1>
<h2>{{item.item_des}}</h2>
<h3>{{item.item_price}}</h3>
{%endblock%}

mysite/food/templates/food/index.html
{% extends 'food/base.html'%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    {%block body%}
    {%for item in item_list%}
        <div class="row">
            <div class="col-md-3 offset-md-2">
                <img class="card" height="100px" alt="" src="{{ item.item_image}}">
            </div>
        </div>
        <div class="col-md-4">
            <h3>{{item.item_name}}</h3>
            <h5>{{item.item_des}}</h5>
            <h6>${{item.item_price}}</h6>
        </div>
        <div class="col-md-2"></div>

    {% endfor %}
    {% endblock %}
    this is old code
    <ul>
        <li>
            <a href={% url 'food:detail' item.id %}>{{item.id}} -- {{item.item_name}} </a>
        </li>
    </ul>

</body>

</html>